#define WIN32_LEAN_AND_MEAN 
#include <Windows.h>
#include <winternl.h>

#include <cstdio>
#include <iostream>
#include <sddl.h>
#include <shellapi.h>
#include <stdio.h>
#include <strsafe.h>
#include <tchar.h>

#include "krabs.hpp"

// enableppl.cpp
void InstallVulnerableDriver();
void EnablePPL();
void DisablePPL();

// loaddriver.cpp
#define IDR_RT_RCDATA1 101

// version.cpp
void PrintVersion();

//
// Microsoft-Windows-Threat-Intelligence ETW 
// https://github.com/jdu2600/Windows10EtwEvents/blob/main/manifest/Microsoft-Windows-Threat-Intelligence.tsv
//

// Event ids
enum ThreatIntelligenceEventId : USHORT
{
    ETW_THREAT_INTEL_INVALID = 0,
    ETW_THREAT_INTEL_ALLOCVM_REMOTE = 1,
    ETW_THREAT_INTEL_PROTECTVM_REMOTE = 2,
    ETW_THREAT_INTEL_MAPVIEW_REMOTE = 3,
    ETW_THREAT_INTEL_QUEUEUSERAPC_REMOTE = 4,
    ETW_THREAT_INTEL_SETTHREADCONTEXT_REMOTE = 5,
    ETW_THREAT_INTEL_ALLOCVM_LOCAL = 6,
    ETW_THREAT_INTEL_PROTECTVM_LOCAL = 7,
    ETW_THREAT_INTEL_MAPVIEW_LOCAL = 8,
    ETW_THREAT_INTEL_READVM_LOCAL = 11,
    ETW_THREAT_INTEL_WRITEVM_LOCAL = 12,
    ETW_THREAT_INTEL_READVM_REMOTE = 13,
    ETW_THREAT_INTEL_WRITEVM_REMOTE = 14,
    ETW_THREAT_INTEL_SUSPEND_THREAD = 15,
    ETW_THREAT_INTEL_RESUME_THREAD = 16,
    ETW_THREAT_INTEL_SUSPEND_PROCESS = 17,
    ETW_THREAT_INTEL_RESUME_PROCESS = 18,
    ETW_THREAT_INTEL_FREEZE_PROCESS = 19,
    ETW_THREAT_INTEL_THAW_PROCESS = 20,
    ETW_THREAT_INTEL_ALLOCVM_REMOTE_KERNEL_CALLER = 21,
    ETW_THREAT_INTEL_PROTECTVM_REMOTE_KERNEL_CALLER = 22,
    ETW_THREAT_INTEL_MAPVIEW_REMOTE_KERNEL_CALLER = 23,
    ETW_THREAT_INTEL_QUEUEUSERAPC_REMOTE_KERNEL_CALLER = 24,
    ETW_THREAT_INTEL_SETTHREADCONTEXT_REMOTE_KERNEL_CALLER = 25,
    ETW_THREAT_INTEL_ALLOCVM_LOCAL_KERNEL_CALLER = 26,
    ETW_THREAT_INTEL_PROTECTVM_LOCAL_KERNEL_CALLER = 27,
    ETW_THREAT_INTEL_MAPVIEW_LOCAL_KERNEL_CALLER = 28,
    ETW_THREAT_INTEL_DRIVER_CREATE = 29,
    ETW_THREAT_INTEL_DRIVER_DELETE = 30,
    ETW_THREAT_INTEL_DEVICE_CREATE = 31,
    ETW_THREAT_INTEL_DEVICE_DELETE = 32,
};

// keywords
constexpr ULONGLONG ETW_THREAT_INTEL_KEYWORD_ALLOCVM_LOCAL = 0x1;
constexpr ULONGLONG ETW_THREAT_INTEL_KEYWORD_ALLOCVM_LOCAL_KERNEL_CALLER = 0x2;
constexpr ULONGLONG ETW_THREAT_INTEL_KEYWORD_ALLOCVM_REMOTE = 0x4;
constexpr ULONGLONG ETW_THREAT_INTEL_KEYWORD_ALLOCVM_REMOTE_KERNEL_CALLER = 0x8;
constexpr ULONGLONG ETW_THREAT_INTEL_KEYWORD_PROTECTVM_LOCAL = 0x10;
constexpr ULONGLONG ETW_THREAT_INTEL_KEYWORD_PROTECTVM_LOCAL_KERNEL_CALLER = 0x20;
constexpr ULONGLONG ETW_THREAT_INTEL_KEYWORD_PROTECTVM_REMOTE = 0x40;
constexpr ULONGLONG ETW_THREAT_INTEL_KEYWORD_PROTECTVM_REMOTE_KERNEL_CALLER = 0x80;
constexpr ULONGLONG ETW_THREAT_INTEL_KEYWORD_MAPVIEW_LOCAL = 0x100;
constexpr ULONGLONG ETW_THREAT_INTEL_KEYWORD_MAPVIEW_LOCAL_KERNEL_CALLER = 0x200;
constexpr ULONGLONG ETW_THREAT_INTEL_KEYWORD_MAPVIEW_REMOTE = 0x400;
constexpr ULONGLONG ETW_THREAT_INTEL_KEYWORD_MAPVIEW_REMOTE_KERNEL_CALLER = 0x800;
constexpr ULONGLONG ETW_THREAT_INTEL_KEYWORD_QUEUEUSERAPC_REMOTE = 0x1000;
constexpr ULONGLONG ETW_THREAT_INTEL_KEYWORD_QUEUEUSERAPC_REMOTE_KERNEL_CALLER = 0x2000;
constexpr ULONGLONG ETW_THREAT_INTEL_KEYWORD_SETTHREADCONTEXT_REMOTE = 0x4000;
constexpr ULONGLONG ETW_THREAT_INTEL_KEYWORD_SETTHREADCONTEXT_REMOTE_KERNEL_CALLER = 0x8000;
constexpr ULONGLONG ETW_THREAT_INTEL_KEYWORD_CONTEXT_PARSE = 0x4000000;
constexpr ULONGLONG ETW_THREAT_INTEL_KEYWORD_READVM_REMOTE = 0x20000;
constexpr ULONGLONG ETW_THREAT_INTEL_KEYWORD_WRITEVM_LOCAL = 0x40000;
constexpr ULONGLONG ETW_THREAT_INTEL_KEYWORD_WRITEVM_REMOTE = 0x80000;
constexpr ULONGLONG ETW_THREAT_INTEL_KEYWORD_SUSPEND_THREAD = 0x100000;
constexpr ULONGLONG ETW_THREAT_INTEL_KEYWORD_SUSPEND_PROCESS = 0x400000;
constexpr ULONGLONG ETW_THREAT_INTEL_KEYWORD_FREEZE_PROCESS = 0x1000000;
constexpr ULONGLONG ETW_THREAT_INTEL_KEYWORD_DEVICE_EVENTS = 0x80000000;

// keyword helpers
constexpr ULONGLONG ETW_THREAT_INTEL_KEYWORDS_VIRTUALALLOC = ETW_THREAT_INTEL_KEYWORD_ALLOCVM_LOCAL | ETW_THREAT_INTEL_KEYWORD_ALLOCVM_LOCAL_KERNEL_CALLER;
constexpr ULONGLONG ETW_THREAT_INTEL_KEYWORDS_VIRTUALALLOCEX = ETW_THREAT_INTEL_KEYWORD_ALLOCVM_REMOTE | ETW_THREAT_INTEL_KEYWORD_ALLOCVM_REMOTE_KERNEL_CALLER;
constexpr ULONGLONG ETW_THREAT_INTEL_KEYWORDS_VIRTUALPROTECT = ETW_THREAT_INTEL_KEYWORD_PROTECTVM_LOCAL | ETW_THREAT_INTEL_KEYWORD_PROTECTVM_LOCAL_KERNEL_CALLER;
constexpr ULONGLONG ETW_THREAT_INTEL_KEYWORDS_VIRTUALPROTECTEX = ETW_THREAT_INTEL_KEYWORD_PROTECTVM_REMOTE | ETW_THREAT_INTEL_KEYWORD_PROTECTVM_REMOTE_KERNEL_CALLER;
constexpr ULONGLONG ETW_THREAT_INTEL_KEYWORDS_MAPVIEW = ETW_THREAT_INTEL_KEYWORD_MAPVIEW_LOCAL | ETW_THREAT_INTEL_KEYWORD_MAPVIEW_LOCAL_KERNEL_CALLER;
constexpr ULONGLONG ETW_THREAT_INTEL_KEYWORDS_MAPVIEW2 = ETW_THREAT_INTEL_KEYWORD_MAPVIEW_REMOTE | ETW_THREAT_INTEL_KEYWORD_MAPVIEW_REMOTE_KERNEL_CALLER;
constexpr ULONGLONG ETW_THREAT_INTEL_KEYWORDS_QUEUEUSERAPC = ETW_THREAT_INTEL_KEYWORD_QUEUEUSERAPC_REMOTE | ETW_THREAT_INTEL_KEYWORD_QUEUEUSERAPC_REMOTE_KERNEL_CALLER;
constexpr ULONGLONG ETW_THREAT_INTEL_KEYWORDS_SETTHREADCONTEXT = ETW_THREAT_INTEL_KEYWORD_SETTHREADCONTEXT_REMOTE | ETW_THREAT_INTEL_KEYWORD_SETTHREADCONTEXT_REMOTE_KERNEL_CALLER | ETW_THREAT_INTEL_KEYWORD_CONTEXT_PARSE;
constexpr ULONGLONG ETW_THREAT_INTEL_KEYWORDS_WRITEPROCESSMEMORY = ETW_THREAT_INTEL_KEYWORD_WRITEVM_LOCAL | ETW_THREAT_INTEL_KEYWORD_WRITEVM_REMOTE;
constexpr ULONGLONG ETW_THREAT_INTEL_KEYWORDS_SUSPEND_PROCESS = ETW_THREAT_INTEL_KEYWORD_SUSPEND_PROCESS | ETW_THREAT_INTEL_KEYWORD_FREEZE_PROCESS;
constexpr ULONGLONG ETW_THREAT_INTEL_KEYWORDS_SUSPEND = ETW_THREAT_INTEL_KEYWORD_SUSPEND_THREAD | ETW_THREAT_INTEL_KEYWORDS_SUSPEND_PROCESS;
constexpr ULONGLONG ETW_THREAT_INTEL_KEYWORDS_IOCREATEDEVICE = ETW_THREAT_INTEL_KEYWORD_DEVICE_EVENTS;